management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always

management.tracing.enabled=true

management.otlp.tracing.endpoint=http://tempo.tempo.svc.cluster.local:4318/v1/traces

management.otlp.tracing.transport=http

management.metrics.export.prometheus.enabled=true
