apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot

spec:
  replicas: 2

  selector:
    matchLabels:
      app: springboot

  template:
    metadata:
      labels:
        app: springboot

    spec:
      containers:
        - name: springboot

          image: 136863648867.dkr.ecr.us-east-1.amazonaws.com/platform-demo:4cc53bf1192dfb386a03d125a4dcd7142cd6e18a

          ports:
            - containerPort: 8080

          env:
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: username

            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: password

            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: apiKey

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
