apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot

spec:
  replicas: 2

  selector:
    matchLabels:
      app: springboot

  template:
    metadata:
      labels:
        app: springboot

    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: springboot

          image: 136863648867.dkr.ecr.us-east-1.amazonaws.com/platform-demo:90852d5d2f0eb6cc7f15d77be3e45718df230ab2

          securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001

                allowPrivilegeEscalation: false

                capabilities:
                  drop:
                    - ALL

                #readOnlyRootFilesystem: true

                seccompProfile:
                  type: RuntimeDefault

          ports:
            - containerPort: 8080

          env:
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: username

            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: password

            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: apiKey

            - name: OTEL_SERVICE_NAME
              value: platform-demo

            - name: OTEL_TRACES_EXPORTER
              value: otlp

            - name: OTEL_METRICS_EXPORTER
              value: none

            - name: OTEL_LOGS_EXPORTER
              value: none

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.tempo.svc.cluster.local:4318

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
