apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    external-dns.alpha.kubernetes.io/hostname: springboot.dev.learnsystems.co

spec:
  ingressClassName: alb

  rules:
    - host: springboot.dev.learnsystems.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot
                port:
                  number: 80
