apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:

  project: platform

  source:
    repoURL: https://github.com/ckalandar/aws-platform-engineering.git
    targetRevision: main
    path: gitops/manifests/aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true