apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "0"

spec:

  project: default

  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

  sources:

    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 78.0.0

      helm:
        skipCrds: true
        valueFiles:
          - $values/gitops/values/monitoring/dev.yaml

    - repoURL: https://github.com/ckalandar/aws-platform-engineering.git
      targetRevision: main
      ref: values

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
