apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tempo
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: tempo

  sources:

    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.23.2

      helm:
        valueFiles:
          - $values/gitops/values/tempo/dev.yaml

    - repoURL: https://github.com/ckalandar/aws-platform-engineering.git
      targetRevision: dev-floci
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
