apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: springboot
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ckalandar/aws-platform-engineering.git
    targetRevision: main
    path: gitops/manifests/springboot

  destination:
    server: https://kubernetes.default.svc
    namespace: springboot

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true