apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - readonly-role.yaml
  - readonly-binding.yaml
  - namespace-admin-role.yaml
  - namespace-admin-binding.yaml
  - observability-role.yaml
  - observability-binding.yaml
