apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: namespace-admin
  namespace: springboot

subjects:

- kind: Group
  name: app-team

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
