apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: platform-readonly

rules:

- apiGroups: [""]
  resources:
    - pods
    - services
    - configmaps
    - endpoints
    - namespaces
  verbs:
    - get
    - list
    - watch

- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
  verbs:
    - get
    - list
    - watch

- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
