apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: springboot
  namespace: springboot

subjects:

  - kind: ServiceAccount
    name: springboot
    namespace: springboot

roleRef:
  kind: Role
  name: springboot
  apiGroup: rbac.authorization.k8s.io
