grafana:

  adminPassword: admin123

  service:
    type: ClusterIP

  ingress:
    enabled: true

    ingressClassName: alb

    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip

    hosts:
      - grafana.dev.learnsystems.co
  additionalDataSources:

    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.loki.svc.cluster.local
      isDefault: false
prometheus:
  prometheusSpec:

    retention: 15d

    storageSpec:

      volumeClaimTemplate:

        spec:

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 20Gi

alertmanager:

  alertmanagerSpec:

    storage:

      volumeClaimTemplate:

        spec:

          accessModes:
            - ReadWriteOnce

          resources:

            requests:
              storage: 5Gi
