apiVersion: v1
items:
- apiVersion: external-secrets.io/v1
  kind: ExternalSecret
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: external-secrets-prereqs:external-secrets.io/ExternalSecret:springboot/app-config
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"external-secrets.io/v1","kind":"ExternalSecret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"external-secrets-prereqs:external-secrets.io/ExternalSecret:springboot/app-config"},"name":"app-config","namespace":"springboot"},"spec":{"data":[{"remoteRef":{"key":"springboot/dev/app-config","property":"username"},"secretKey":"username"},{"remoteRef":{"key":"springboot/dev/app-config","property":"password"},"secretKey":"password"},{"remoteRef":{"key":"springboot/dev/app-config","property":"apiKey"},"secretKey":"apiKey"}],"refreshInterval":"1m","secretStoreRef":{"kind":"ClusterSecretStore","name":"aws-secretsmanager"},"target":{"name":"app-config"}}}
    creationTimestamp: "2026-07-30T11:28:50Z"
    generation: 2
    name: app-config
    namespace: springboot
    resourceVersion: "1555662"
    uid: 58f7bf01-6bcf-44ff-8c94-17c0a007e261
  spec:
    data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: springboot/dev/app-config
        metadataPolicy: None
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: springboot/dev/app-config
        metadataPolicy: None
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: springboot/dev/app-config
        metadataPolicy: None
        property: apiKey
      secretKey: apiKey
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-secretsmanager
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: app-config
  status:
    binding:
      name: app-config
    conditions:
    - lastTransitionTime: "2026-07-30T12:19:19Z"
      message: secret synced
      reason: SecretSynced
      status: "True"
      type: Ready
    refreshTime: "2026-08-02T16:47:25Z"
    syncedResourceVersion: 2-781530c829a3364c9841479d2369fc468b3563c45ca2d385d3635097
kind: List
metadata:
  resourceVersion: ""
