name: SpringBoot CI

on:
  push:
    branches:
      - main
    paths:
      - "gitops/applications/springboot-app/**"

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: platform-demo

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gitops/applications/springboot-app

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Jar
        run: mvn clean package

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${{ github.sha }} \
            .

      - name: Tag Image
        run: |
          docker tag \
          $ECR_REPOSITORY:${{ github.sha }} \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      - name: Update GitOps Manifest
        run: |
          sed -i "s|image: .*|image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}|g" \
          gitops/manifests/springboot/deployment.yaml

      - name: Commit Manifest
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

          git add gitops/manifests/springboot/deployment.yaml

          git commit -m "Update image to ${{ github.sha }}" || true

          git push
